### ISSUE TITLE
[TEST] Запуск тестов до coverage

### ISSUE THREAD

**Issue by generalova-kate** [nn-students-2020h1/team-number-two-#11]
Сначало нужно запустить тесты, а потом coverage. Coverage строится на данных от тестов.
https://github.com/nn-students-2020h1/team-number-two-/blob/1ed54cf809882853fd733b1e2826b2ad3f44a6f2/.github/workflows/pythonpackage.yml#L38

**Comment by Poshushukaemsya** [comment]
исправлено
